name: "Test Suite"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Disable CI checks
        run: echo "CI=false" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run cargo tests
        run: cargo test --all-features
        working-directory: ./backend
