name: "Test Suite"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Set RUSTFLAGS to not treat warnings as errors
        run: echo "RUSTFLAGS='-A warnings'" >> $GITHUB_ENV
      - name: Run cargo tests
        run: cargo test --all-features
        working-directory: ./backend
